services:
  app:
    build: .docker
    stdin_open: true
    tty: true
    container_name: app.Proiect_An_Vue_API
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 100
    ports:
       - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.git/
    working_dir: /app
    user: root

  api:
     build: .docker/api
     stdin_open: true
     tty: true
     container_name: api.Proiect_An_Vue_API
     environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 100
     ports:
      - "3000:3000"
     volumes:
      - ./api:/api
      # exclude
      # - /api/.git/
     working_dir: /api
     user: 1000:1000

  ws:
    build: .docker/ws
    stdin_open: true
    tty: true
    container_name: ws.Proiect_An_Vue_API
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      CHOKIDAR_INTERVAL: 100
    ports:
      - "3001:3001"
    volumes:
      - ./ws:/ws
      # exclude
      # - /ws/.git/
    working_dir: /ws
    user: 1000:1000

  mysql:
     image: mysql:8.0.40
     container_name: mysql.Proiect_An_Vue_API
     ports:
      - "3306:3306"
     environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: Proiect_An_Vue_API
      MYSQL_USER: Proiect_An_Vue_API
      MYSQL_PASSWORD: Proiect_An_Vue_API
     volumes:
      - mysql_data:/var/lib/mysql
      - ./.docker/mysql/utf8mb4.cnf:/etc/mysql/conf.d/utf8mb4.cnf:ro
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database:/database:rw
     restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: pma.Proiect_An_Vue_API
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql.Proiect_An_Vue_API
      PMA_USER: Proiect_An_Vue_API
      PMA_PASSWORD: Proiect_An_Vue_API
      UPLOAD_LIMIT: 250M
    #networks:
      #- default
    restart: always

volumes:
  mysql_data:
    driver: local

